---
- name: Deploying Metadata Service Container in local
  hosts: appserver
  become: true

  vars:
    image_name: "preethi536/metadata-service-image"
    container_name: "metadata-service"
    host_port: "9090" 
    container_port: "8080"

  tasks:
    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull Docker image for this build
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ build_number }}"
        source: pull

    - name: Run latest container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}:{{ build_number }}"
        state: started
        recreate: true
        ports:
          - "{{ host_port }}:{{ container_port }}"
          env:
          MONGO_USERNAME: "{{ MONGO_USERNAME }}"
          MONGO_PASSWORD: "{{ MONGO_PASSWORD }}"
          MONGO_HOST: "{{ MONGO_HOST }}"
          MONGO_DB: "{{ MONGO_DB }}"         
